"""APEX 3.2 Smoking-Gun Regression Test (Step 107 Audit).

Verifies that on Step 107 (Day 4, Hour 11, Cash $341):
1. No artificial SELL WHEAT 1 candidate is generated by ActionPlanner.
2. APEX 3.2 produces the EXACT UNCHANGED V4.1 MASTER BASELINE ACTION.
3. Fallback mechanism returns base_action with 0 unwanted market clutter.
"""

from __future__ import annotations
import sys
import os
import importlib.util

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

import kaggle_environments

def load_v41_baseline():
    v41_path = os.path.join(BASE_DIR, "baseline", "kaitofukami-v18.py")
    spec = importlib.util.spec_from_file_location("v41_mod", v41_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.agent

v41_agent = load_v41_baseline()

from apex.world_model import WorldState
from apex.planner import ActionPlanner
from apex.empirical_mcv_evaluator31 import EmpiricalMarginalEvaluator31
from apex.counterfactual import CounterfactualSimulator
from apex.divergence_controller import DivergenceController

_APEX32_CONTROLLER = DivergenceController(max_deviations_per_episode=1)

def run_apex32_agent(obs, conf=None):
    base_action = v41_agent(obs)
    wstate = WorldState(obs)
    if wstate.step == 0:
        _APEX32_CONTROLLER.reset_episode()

    if wstate.remaining_steps <= 24 or wstate.step < 100 or wstate.step > 600:
        return base_action

    candidates = ActionPlanner.generate_market_candidates(wstate, base_action)
    approved = []

    for cand in candidates:
        approved_cand, mcv_score, reason = CounterfactualSimulator.evaluate_exploration_candidate(
            cand, base_action, wstate, evaluator_cls=EmpiricalMarginalEvaluator31
        )
        if approved_cand and mcv_score >= 1.0:
            approved.append((mcv_score, cand, reason))

    chosen = _APEX32_CONTROLLER.select_controlled_deviation(approved, wstate)
    if chosen is not None:
        first_ord = chosen.candidate[0] if isinstance(chosen.candidate, list) and len(chosen.candidate) > 0 else chosen.candidate
        if isinstance(first_ord, list) and len(first_ord) > 0 and isinstance(first_ord[0], list):
            first_ord = first_ord[0]

        alt_market = list(base_action.get("market", [])) + [first_ord]
        apex_action = dict(base_action)
        apex_action["market"] = alt_market
        return apex_action

    return base_action

def test_step107_regression():
    print("==================================================================================", flush=True)
    print("🧪 APEX 3.2 SMOKING-GUN REGRESSION TEST (STEP 107 AUDIT)", flush=True)
    print("==================================================================================", flush=True)

    test_seeds = [777001, 777005, 590244349]
    all_passed = True

    for seed in test_seeds:
        env = kaggle_environments.make("kaggriculture", configuration={"episodeSteps": 720, "townCenterSellInterval": 24, "seed": seed})
        trainer = env.train([None, v41_agent])
        obs = trainer.reset()

        step107_divergence = False

        for step_idx in range(720):
            act_v41 = v41_agent(obs)
            act_apex32 = run_apex32_agent(obs)

            if step_idx == 107:
                v41_market = act_v41.get("market", [])
                apex_market = act_apex32.get("market", [])
                has_artificial_wheat = any(m[0] == "SELL" and len(m) > 1 and m[1] == "WHEAT" for m in apex_market)
                
                print(f"Seed {seed} | Step 107 Audit:")
                print(f"  ├── V4.1 Base Market Action  : {v41_market}")
                print(f"  ├── APEX 3.2 Market Action   : {apex_market}")
                print(f"  └── Artificial Wheat Present : {'YES ❌ (FAILED)' if has_artificial_wheat else 'NO ✅ (PASSED)'}")

                if has_artificial_wheat or act_v41 != act_apex32:
                    step107_divergence = True
                    all_passed = False

            obs, reward, done, info = trainer.step(act_apex32)
            if done:
                break

    print("----------------------------------------------------------------------------------")
    print(f"REGRESSION TEST VERDICT: {'ALL SEEDS PASSED 100% CLEANLY ✅' if all_passed else 'FAILED ❌'}")
    print("==================================================================================", flush=True)

if __name__ == "__main__":
    test_step107_regression()
